language: php

 php:
   - 5.4
   - 5.5
   - 5.6
   - 7.0

 before_script:
    - composer install --dev

    jobs:
        allow_failures:
        - php: 7.0
          env: KEY=VALUE

 script: ./build.sh


 notifications:
     email:
         - wilberamp@hotmail.com


    
