language: php

 php:
   - 7.0

 before_script:
    - composer install --dev

    jobs:
        allow_failures:
        - php: 7.0
          env: KEY=VALUE

 notifications:
     email:
         - wilberamp@hotmail.com


    
